# Generated by Django 3.1 on 2020-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(blank=True, max_length=20, null=True)),
                ('sap_old', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('cat_id', models.IntegerField(blank=True, null=True)),
                ('subcat_id', models.IntegerField(blank=True, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('resp_id', models.IntegerField(blank=True, null=True)),
                ('date_open', models.DateTimeField(blank=True, null=True)),
                ('date_assign', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('secondname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cat_id', models.IntegerField()),
                ('subcat_info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ipv4', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dolzhnost', models.CharField(blank=True, max_length=150, null=True)),
                ('main_id', models.IntegerField(blank=True, null=True)),
                ('list_id', models.IntegerField(blank=True, null=True)),
                ('sub_id', models.IntegerField(blank=True, null=True)),
                ('squad_id', models.IntegerField(blank=True, null=True)),
                ('manager', models.IntegerField(blank=True, null=True)),
                ('supervisor', models.IntegerField(blank=True, null=True)),
                ('superior', models.IntegerField(blank=True, null=True)),
                ('director', models.IntegerField(blank=True, null=True)),
                ('superadmin', models.IntegerField(blank=True, null=True)),
                ('disabled', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
