# Generated by Django 3.1 on 2020-09-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='sap',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
